#pragma once

#define CHAMPKEY L"ChampName"
#define MOVEPOINT L"MOVEPOINT"
#define MOVECOOL L"MOVECOOL"

#define ARCHER L"Champ_Archer"
#define KNIGHT L"Champ_Knight"

#define DMGNUMB_0	L"dmg_0"
#define DMGNUMB_1	L"dmg_1"
#define DMGNUMB_2	L"dmg_2"
#define DMGNUMB_3	L"dmg_3"
#define DMGNUMB_4	L"dmg_4"
#define DMGNUMB_5	L"dmg_5"
#define DMGNUMB_6	L"dmg_6"
#define DMGNUMB_7	L"dmg_7"
#define DMGNUMB_8	L"dmg_8"
#define DMGNUMB_9	L"dmg_9"
#define HEALNUMB_0	L"heal_0"
#define HEALNUMB_1	L"heal_1"
#define HEALNUMB_2	L"heal_2"
#define HEALNUMB_3	L"heal_3"
#define HEALNUMB_4	L"heal_4"
#define HEALNUMB_5	L"heal_5"
#define HEALNUMB_6	L"heal_6"
#define HEALNUMB_7	L"heal_7"
#define HEALNUMB_8	L"heal_8"
#define HEALNUMB_9	L"heal_9"